// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../components.plugin").default> &
  InjectionType<typeof import("../../../../node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin").default> &
  InjectionType<typeof import("../../../../node_modules/nuxt/dist/head/runtime/mixin-plugin").default> &
  InjectionType<typeof import("../../../../node_modules/nuxt/dist/pages/runtime/router").default> &
  InjectionType<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/plugins/documentDriven").default> &
  InjectionType<typeof import("../../../../node_modules/@nuxt/content/dist/runtime/plugins/ws").default> &
  InjectionType<typeof import("../../../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server").default> &
  InjectionType<typeof import("../../../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client").default> &
  InjectionType<typeof import("../pinceau-imports").default> &
  InjectionType<typeof import("../../../../node_modules/nuxt/dist/app/plugins/payload.client").default> &
  InjectionType<typeof import("../../../../node_modules/@nuxt-themes/docus-edge/plugins/menu").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
