// Generated by components discovery
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'VButton': typeof import('@vunix/core/dist/runtime/components')['VButton']
  }
}

export const VButton: typeof import('@vunix/core/dist/runtime/components')['VButton']

export const componentNames: string[]