// Generated by components discovery
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'DwButton': typeof import('@vunix/core/dist/runtime/components')['DwButton']
  }
}

export const DwButton: typeof import('@vunix/core/dist/runtime/components')['DwButton']

export const componentNames: string[]